# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    locale: 'en'
    frontend_url: '%env(FRONTEND_URL)%'
    app.base_url: '%env(APP_BASE_URL)%'
    # üñºÔ∏è PARAM√àTRES POUR LA GESTION DES FICHIERS (IMAGE D'√âV√âNEMENT)
    # Chemin absolu o√π les images seront stock√©es (ex: /var/www/project/public/uploads/events)
    event_images_directory: '%kernel.project_dir%/public/uploads/events'
    # Chemin public (URL) stock√© en BDD et utilis√© pour l'affichage (ex: uploads/events)
    event_images_public_path: 'uploads/events'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
    App\Controller\EventController:
        arguments:
            # Mappe l'argument $eventImagesDirectory du constructeur au param√®tre
            $eventImagesDirectory: '%event_images_directory%'
            # Mappe l'argument $eventImagesPublicPath du constructeur au param√®tre
            $eventImagesPublicPath: '%event_images_public_path%'  
     # Configuration du nouveau service
    App\Service\ProfilePictureService:
        arguments:
            # Injection de l'URL de base d√©finie dans les param√®tres
            $baseUrl: '%app.base_url%'          
    App\EventListener\AuthenticationSuccessListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccess }
           # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\EventListener\UserActivityListener:
        arguments:
            $em: '@doctrine.orm.entity_manager'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
 