security:
    #enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 
            algorithm: auto 
            cost: 10

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        main:
            lazy: true
            provider: app_user_provider
            stateless: true

            # JSON login pour /api/login_check
            json_login:
                check_path: /api/login_check
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

            # JWT pour les autres endpoints API
            jwt: ~

    access_control:
        - { path: ^/api/verify-code, roles: PUBLIC_ACCESS }
        - { path: ^/api/users, methods: [POST], roles: PUBLIC_ACCESS }
        - { path: ^/api/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/docs, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/events, roles: IS_AUTHENTICATED_FULLY }